title: Small Army Of Nerds
email: jamie@smallarmyofnerds.com
description: >
  Small Army Of Nerds is a software and technology consulting business providing a broad array
  of services to multiple industries.
baseurl: ""
url: "https://smallarmyofnerds.com"
twitter_username: armyofnerds
github_username:  jamiehale

header_pages:
  - about.md
  - projects.md
  - staff.md
  - software.md

markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
source: src
future: true
