# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    working_directory: ~/src
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: build
          command: JEKYLL_ENV=production bundle exec jekyll build
      - run:
          name: run tests
          command: bundle exec htmlproofer ./_site --check-html --disable-external
      - run:
          name: deploy
          command: |
            sudo apt install rsync
            rsync -va -e "ssh -o StrictHostKeyChecking=no" --delete ./_site/* circleci@smallarmyofnerds.com:/var/www/smallarmyofnerds.com/public
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
